### PR TITLE
Proper handling of exceptions during DicomClient.Send(Async). Connected to #239

### LINKED ISSUE #239: DicomClient.Send DicomAssociationRejectedException not working
Sorry, did not found a nice title ...

Running the code

            DicomClient client = new DicomClient();
            DicomCEchoRequest echoRequest = new DicomCEchoRequest();
            client.AddRequest(echoRequest);
            try
            {
                client.Send("127.0.0.1", 3000, false, "Me", "You");
            }
            catch (Exception ex)
            {
                Logger ...
            }
does not hit the Logger when the association is rejected, I expected a `DicomAssociationRejectedException`.

I am no expert in best "awaiting" patterns, but it seems the issue is caused basically by 

            public void OnReceiveAssociationReject(
                DicomRejectResult result,
                DicomRejectSource source,
                DicomRejectReason reason)
            {
                this.SetComplete();
                throw new DicomAssociationRejectedException(result, source, reason);
            }

I see the exception is thrown, but my above code is done already!

I think the SetComplete() should be changed to something like

            private void SetComplete(Exception ex = null)
            {
                if (this.client.completeNotifier != null)
                {
                    if (ex == null)
                    {
                        this.client.completeNotifier.TrySetResult(true);
                    }
                    else
                    {
                        this.client.completeNotifier.TrySetException(ex);
                    }
                }
            }

and the `OnReceiveAssociationReject` should just call `this.SetComplete(new DicomAssociationRejectedException(result, source, reason));`. The `OnReceiveAbort` should act accordingly.
At least now I am receiving an exception in my upper "high level" code, but it is an `AggregateException`. To make the behaviour the same no matter if you are using `client.Send(..)` or `await client.SendAsync(..)`.
I propose to change the synchron `Send(..)` implementations to something like:

            try
            {
                this.InitializeSend(this.networkStream, assoc);
                this.completeNotifier.Task.Wait();
            }
            catch (AggregateException ex)
            {
                throw ex.InnerException;
            }
            finally
            {
                this.FinalizeSend();
            }

But again, I am no expert in TPL.
And I need to investigate in "Forks" and "Pull requests" ...

### PR DESCRIPTION
**Pull request by anders9ustafsson**
Fixes #239 (according to @Ed55 's proposals).

Changes proposed in this pull request:
- Re-factor `SetComplete` method to handle optional exceptions.
- Unwrap `AggregateException` and re-throw the inner exceptions in the `Send` overloads.
- Re-factor the actual send parts in the `Send` and `SendAsync` overloads to be contained in separate `DoSend(Async)` methods.

Please review.

### CODE REVIEW

File: DICOM/Network/DicomClient.cs [hunk 1]
```diff
@@ -320,6 +312,33 @@ public void Abort()
...
+        private void DoSend(INetworkStream stream, DicomAssociation assoc)
+        {
+            try
+            {
+                this.InitializeSend(stream, assoc);
+                this.completeNotifier.Task.Wait();
+            }
+            catch (AggregateException ae)
+            {
+                foreach (var e in ae.Flatten().InnerExceptions)
```
Comment (IanYates) [inline DICOM/Network/DicomClient.cs]: This would just throw the very first exception and lose the rest of them.  We could just do a .First() in that case?

Looking at https://msdn.microsoft.com/en-us/library/dd997415(v=vs.110).aspx it seems we could `throw ae.Flatten()` which would unwrap nested AggregateException instances.  But the caller would still get AggregateException I think (just not so nested)...

**Comment by IanYates** [comment]
:+1:

File: DICOM/Network/DicomClient.cs (hunk 1 above)
Comment (anders9ustafsson) [inline DICOM/Network/DicomClient.cs]: @IanYates Yes, you are right of course. Since this would normally yield one single exception, I might as well re-throw the first. Hold on for the update, and thanks for reviewing!

**Comment by Ed55** [comment]
Isn't this identical to ae.InnerException ?

**Comment by anders9ustafsson** [comment]
@IanYates Yes, you are right again, according to the .NET Reference Source. As we say in Sweden "crossing the creek to fetch water" :-) I'll keep the `Flatten()` call just to be sure; in theory the first inner exception *could* still be an `AggregateException`, right?

**Comment by Ed55** [comment]
@anders9ustafsson you are right, Flatten() flattens :-D
