### PR TITLE
Fix bug: It's very slow open deflated file

### LINKED ISSUE #1115: It's very slow to open deflated dicom file
**Describe the bug**
It takes about 5 min to open a 40MB deflated DICOM file .

The root cause is [code](https://github.com/fo-dicom/fo-dicom/blob/15258dbe7177a09c18b70be4757d25b444bcedc2/DICOM/IO/Reader/DicomReader.cs#L302) - it read whole file byte by byte.

**To Reproduce**
*   Open a 40MB deflated DICOM file

**Expected behavior**
* It should take a few seconds to complete 

**Actual behavior**
* It takes about 5 min

**Screenshots or test DICOM files**
[Deflated.zip](https://github.com/fo-dicom/fo-dicom/files/5308563/Deflated.zip)
Note: it's not a good idea to upload a 40MB file, so I attached a 4MB file as example. It takes 6 seconds to open, while after my fix, it takes only 0.3 second.

**Environment**
DICOM version: (4.0.6)
OS: ( Windows 10 x64)
Platform: (.NET Core)
CPU:  I7-8665U
MEM: 48GB

### PR DESCRIPTION
**Pull request by pengchen0692**
Fixes #1115 .

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Add GetStream to IByteSource
- FileByteSource expose internal stream directly for DicomReader to consume

#### Notes
- GivenDeflatedDicomFileWithSequence_WhenOpenFile_ThenShouldSucceed in [DicomReaderTests.cs](https://github.com/fo-dicom/fo-dicom/blob/15258dbe7177a09c18b70be4757d25b444bcedc2/Tests/Desktop/IO/Reader/DicomReaderTest.cs#L60) can cover the change
- Please let me know if also need to update FellowOakDicom

### CODE REVIEW

File: DICOM/IO/IByteSource.cs [hunk 1]
```diff
@@ -176,5 +177,11 @@ public interface IByteSource
         /// <param name="state">Callback state.</param>
         /// <returns>true if source contains sufficient number of remaining bytes, false otherwise.</returns>
         bool Require(uint count, ByteSourceCallback callback, object state);
+
+        /// <summary>
+        /// Get stream of this byte source.
+        /// </summary>
+        /// <returns>The stream.</returns>
+        Stream GetStream();
```
Comment (amoerie) [inline DICOM/IO/IByteSource.cs:185]: This could be a get-only property instead of a method, which would be more inline with conventional C#. 

Stream Stream { get; }

File: DICOM/IO/Buffer/ByteBufferByteSource.cs [hunk 2]
```diff
@@ -448,6 +449,20 @@ private byte NextByte()
             }
         }
 
+        public Stream GetStream()
+        {
+            lock (_lock)
```
Comment (amoerie) [inline DICOM/IO/Buffer/ByteBufferByteSource.cs:454]: Would it make sense here to memorize the created stream instead of always creating a new one?

File: DICOM/IO/IByteSource.cs (hunk 1 above)
Comment (pengchen0692) [reply DICOM/IO/IByteSource.cs:185]: yes, it works for FileByteSource and StreamByteSource, but not ByteBufferByteSource...

File: DICOM/IO/Buffer/ByteBufferByteSource.cs (hunk 2 above)
Comment (pengchen0692) [reply DICOM/IO/Buffer/ByteBufferByteSource.cs:454]: eh.. looks like ByteBufferByteSource  doesn't have an internal stream. :(

Comment (gofal) [reply DICOM/IO/Buffer/ByteBufferByteSource.cs:454]: ByteBufferByteSource is a wrapper around IByteSource for handling Endianess when later to be used with Codecs. it is only used in DicomJpegLosslessDecoeerImpl.cs and DicomRleCodecImpl.Mono.cs. 
The method GetStream() is currently only used when reading the file. So BytebufferByteSource.GetStream() will currently never be called. But maybe in future ...
Adding cached stream here did not make any difference in current Benchmark.
