### PR TITLE
Dicom Server listener consumes large amount of memory if http request is sent to listener. Connected to #327

### LINKED ISSUE #327: Dicom Server listener consumes large amount of memory if http request is sent to listener.
I came across this completely by accident and not sure if this would be a real world issue.  However I could see this potentially being a problem.  
### Expected behavior

Close a non Dicom Connection.
### Actual behavior

Connection stays open and memory is consumed.
### Steps to reproduce the behavior

Start a DicomServer listener.  Open a web browser and navigate to http://IP:port of the DicomServer listener.  The listener seems to consume a large amount of memory that is never released.  Even when the web browser or socket is closed.  No errors seem to be logged.

image
### fo-dicom version and OS/platform

Tested on 2 and Beta 3.

### PR DESCRIPTION
**Pull request by Thunderstriker**
Fixes #327 

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
instead of resizing the array based on the length in the PDU we try to read the the complete length in chunks of 1K so we only allocate the full length if we read that amount of data from the network stream

### CODE REVIEW

File: DICOM/Network/DicomService.cs [hunk 1]
```diff
@@ -369,29 +369,32 @@ protected virtual DicomFile GetCStoreDicomFile()
...
-                        }
-
-                        _readLength -= count;
-                        if (_readLength > 0)
+                        ms.Write(buffer, 0, buffer.Length);
+                        while (_readLength > 0)
                         {
-                            count =
-                                await stream.ReadAsync(buffer, buffer.Length - _readLength, _readLength)
+                            int bytesToRead = Math.Min(_readLength, 1024);
```
Comment (anders9ustafsson) [inline DICOM/Network/DicomService.cs]: Should the maximum read size be configurable?

Comment (Thunderstriker) [inline DICOM/Network/DicomService.cs]: The only reason i can imagine is for performance reasons but i didnt do any test.
If you want i can do a few test with different sizes.
Any other reasons you can think of?

Comment (Thunderstriker) [inline DICOM/Network/DicomService.cs]: Did a little test send 10000 echos with size set to 1024 and 8 and 8 is about 2x slower 
We can set the default 16384 (the default maxPduLength in fo-dicom) sothere wil be close to no loss in performance but then when a http request comes in still maximum amoumt of memory wrongly allocated is 16K with is for me acceptable so if we change the defailt to 16384 i see no reason to make it configurable

Comment (anders9ustafsson) [inline DICOM/Network/DicomService.cs]: Actually, if you consider 1024 to be a sufficient number, I am OK to stick with it. But please declare a constant to represent the number for improved readability.

**Comment by Thunderstriker** [comment]
when set to 1024 there is a slight performance loss on large pdu with 16384 there will be close  to no performance hit (on a 32k pdu we will only have to read from the stream 2 times compared 32 time wen set  to 1024).
so i prefer 16384  as it will keep the performance the same and when getting a http request only 16K memory will be allocated instead of 1.3G
