### PR TITLE
Concurrency in DicomDictionary. Connected to #114

### LINKED ISSUE #114: Parallel image creation
*Excerpt from Google Groups question, reported by Yonatan Yaakovian, October 20, 2015:*

I've tried to create multiple DicomDataset using Microsoft's parallel class in order to accelerate export but I got this exception:
"System.ArgumentException: An item with the same key has already been added."   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DicomFellowOak.DicomDictionary.GetPrivateCreator(String creator).
after some research with a college we decided to add a lock on the code block that adds private keys so only one thread will be allowed to add private keys at a given time in order to eliminate possible racing conditions in GetPrivateCreator.
this worked for the last two months but now I get these same exceptions again.

### PR DESCRIPTION
**Pull request by IanYates**
Closes #114

I've evaluated the various code paths and interrelations between the dictionaries and the list and I believe the behaviour should remain correct under multi-threaded use.

### CODE REVIEW

File: DICOM/DicomDictionary.cs [hunk 1]
```diff
@@ -64,15 +66,16 @@ public class DicomDictionary : IEnumerable<DicomDictionaryEntry>
...
+        private ConcurrentDictionary<DicomPrivateCreator, DicomDictionary> _private;
 
-        private IDictionary<DicomTag, DicomDictionaryEntry> _entries;
+        private ConcurrentDictionary<DicomTag, DicomDictionaryEntry> _entries;
 
+        private object _maskedLock;
         private List<DicomDictionaryEntry> _masked;
 
-        private bool _sortMasked;
+        private bool _maskedNeedsSort;
```
Comment (IanYates) [inline DICOM/DicomDictionary.cs]: I felt this name was more clear as to the purpose.  Reading the code the first time, I thought _sortMasked may have meant that _masked was already sorted.

File: DICOM/DicomDictionary.cs [hunk 2]
```diff
@@ -207,13 +217,7 @@ internal set
...
             get
             {
-                DicomDictionary pvt = null;
-                if (!_private.TryGetValue(creator, out pvt))
-                {
-                    pvt = new DicomDictionary(creator);
-                    _private.Add(creator, pvt);
-                }
-                return pvt;
+                return _private.GetOrAdd(creator, _ => new DicomDictionary(creator));
```
Comment (IanYates) [inline DICOM/DicomDictionary.cs]: Style...  I tend to use _ for Func<> parameters that I don't use.  The closure access here to creator isn't really a big deal since the delegate isn't long lived.

File: DICOM/DicomDictionary.cs [hunk 3]
```diff
@@ -236,20 +240,17 @@ public void Add(DicomDictionaryEntry entry)
             }
             else
             {
-                _masked.Add(entry);
-                _sortMasked = true;
+                lock (_maskedLock)
+                {
+                    _masked.Add(entry);
```
Comment (IanYates) [inline DICOM/DicomDictionary.cs]: I don't know how common this operation is, but we could simplify the code if we used a sorted list instead of a plain list.  This would remove the need for a _masked flag altogether.

**Comment by anders9ustafsson** [comment]
@IanYates Great work, many thanks for fixing this!
