### PR TITLE
Optimize DicomTag.GetHashCode

### LINKED ISSUE #1088: DicomTag GetHashCode is grossly inefficient
**Describe the bug**
When parsing a DICOM header, around 50% of all allocations from fo-dicom are stemming from the following lines in `DicomTag`:

```
public override int GetHashCode()
{
            if (_hash == 0) _hash = ToString("X", null).GetHashCode();
            return _hash;
        }
```

This causes a significant performance hit.

**To Reproduce**
Run a memory profiler or a performance benchmark parsing a file, e.g. `DicomFile.Open(content, FileReadOption.Default)` and look at the results

**Expected behavior**
GetHashCode should not allocate anything. Something like: `return unchecked(Group ^ Element)` should be fine, see [Point in System.Drawing reference ](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Point.cs) (and does not need caching)

**Environment**
Fellow Oak DICOM version: 4.0.6

### PR DESCRIPTION
**Pull request by amoerie**
Fixes #1088 .

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] ~~I have updated API documentation~~
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Do not use ToString() in DicomTag.GetHashCode
- Reset cached hash value when setting Private Creator (this field can be publicly set..)
- Add suite of tests that verify we don't produce hash collisions for known DICOM tags
- Fix Service Provider resolution in unit tests when debugging. Some stack frames do not have namespaces, causing null reference exceptions

### CODE REVIEW

**Comment by amoerie** [comment]
I reverted "Dispose ImageSharp image when disposing the Fellow Oak DICOM image", that commit should not have been there, sorry.

**Comment by amoerie** [comment]
Looks like the only failing unit test is one related to the codecs again.

File: Tests/Desktop/DicomTagTest.cs [hunk 1]
```diff
@@ -58,6 +59,118 @@ public void Contains_SamePrivateTagsDifferentPrivateCreator_ReturnsTrue()
             Assert.True(dataset.Contains(new DicomTag(0x3005, 0x1525, "PRIVATE")));
         }
 
+        [Fact]
+        public void GetHashCode_ReturnsValidInt()
+        {
+            var hashCode = DicomTag.AccessionNumber.GetHashCode();
+
+            Assert.InRange(hashCode, 1, int.MaxValue);
```
Comment (gofal) [inline Tests/Desktop/DicomTagTest.cs:67]: this may fail for good reason. Hashcodes have to be integers, but also may be netagive values. So `PrivateCreator.GetHashCode()` may return some negative value anytime.

see here in microsoft doc, there are examples with negative hash-values. https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=netcore-3.1#examples

Comment (amoerie) [reply Tests/Desktop/DicomTagTest.cs:67]: You're right. I forgot to change this unit test to verify that it's not zero, that's the only "invalid value" AFAIK. I'll modify when I get the chance.

**Comment by amoerie** [comment]
I removed the unit test for both v4 and v5. I'm not 100% sure 0 is not a valid hash code, the main purpose of hash codes is to distinguish between objects, so perhaps it's OK. The other unit tests should suffice in validating the hashcode calculation. 

I also removed the cached _hash value, as you showed that it's not really valuable to do so.

**Review by gofal — APPROVED** [review]
